# Generated by Django 2.2 on 2019-08-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Complete', 'Complete')], max_length=100),
        ),
    ]
