# Generated by Django 2.2 on 2019-08-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0002_auto_20190809_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='contact_umber',
            new_name='contact_number',
        ),
    ]
