# Generated by Django 2.2 on 2019-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_clients', '0007_auto_20190811_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
    ]
